import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "./react-slick.css";
import { MUIProvider } from "@/providers";
import Providers from "@/components/auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <MUIProvider>
        <Providers>
          <body className={inter.className}>
            {children}
          </body>
        </Providers>
      </MUIProvider>
    </html>
  );
}
